# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information

workflows:
    react-native-android:
        name: React Native CI/CD compare
        # `mac_pro` - Building on Mac Pro is a paid feature. Please enable billing to run builds on Mac Pro.
        instance_type:  mac_mini
        environment:
            node: latest
        cache:
          cache_paths:
            - ~/.gradle/caches
            - ~/.cache/yarn/v6

        scripts:
            - yarn install --frozen-lockfile
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - cd android && ./gradlew bundleRelease assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
            - android/app/build/outputs/**/*.aab
